version: "3.6"
services:
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: main
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
  api:
    build: ./backend
    ports:
    - "7000:7000"
    environment:
      API_KEY: 76a325g7g2ahs7h4673aa25s47632h5362a4532642
      DB_PORT: 5432
  web:
    build: ./frontend
    ports:
      - "8080:8080"



